admin/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from data import urls as data_urls
from django.conf import settings
from django.conf.urls.static import static
from profiles import urls as profiles_urls
from data.views import CreatePost
from data.views import HomeFeed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include(data_urls)),
    path('', include(profiles_urls)),
    path('create_post/', CreatePost.as_view(), name="create_post"),
    path('home/', HomeFeed.as_view(), name="home"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

data/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'data'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('signup/' ,views.SignUp.as_view(), name='signup'),
    

]

profiles/urls.py
from django.urls import path
from . import views


app_name = 'profiles'

urlpatterns = [
    path('profiles/', views.ProfileView.as_view(), name="profiles"),
    path('profile/', views.AdminProfile.as_view(), name="profile"),
    path('profile/update/', views.ProfileUpdateView.as_view(), name="update-profile"),
    path('detail//user/<int:pk>', views.ProfileDetail.as_view(), name='detail'),


]

data/models.py
from django.db import models
from sorl.thumbnail import ImageField
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    id = models.AutoField(primary_key=True, default=1)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    caption= models.CharField(max_length=500, default="")
    image = models.ImageField(blank=True, null=True)
    
    def __str__(self):
        return self.name
    
    
class ProfileData(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,)
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    image = models.ImageField(upload_to='profiles/', null=True, blank=True)
    bio = models.TextField(max_length=500, null=True, blank=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post', null=True, blank=True)
    password2 = models.CharField(max_length=100);
    def __str__(self):
        return self.name

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
# Create your models here.

    

        

        

data/forms.py
# forms.py
from django import forms
from .models import Post
from .models import ProfileData
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['image', 'caption']
 
        
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()
    
        
        
# class SignupForm(forms.ModelForm):
#     password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)
#     class Meta:
#         model = ProfileData
#         fields = ['name', 'password']
     
    
        
    # def clean_password2(self):
    #     password = self.cleaned_data.get('password')
    #     password2 = self.cleaned_data.get('password2')
    #     if password != password2:
    #         raise forms.ValidationError("Passwords do not match")
    #     return password2
    # def save(self, commit=True):
    #     user = super().save(commit=False)
    #     user.set_password(self.cleaned_data['password'])
    #     if commit:
    #         user.save()
    #     return user

from django import forms
from .models import ProfileData

class SignupForm(forms.ModelForm):
    name=forms.CharField(max_length=100)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'password', 'password2', 'name']

    def clean_password2(self):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password and password2 and password != password2:
            raise forms.ValidationError("Passwords do not match.")
        return password2
    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
            profile = ProfileData(user=user, name=self.cleaned_data['name'])
            profile.save()
        return user
class ProfileUpdateForm(forms.Form):
    class Meta:
        model = ProfileData
        fields = ['name', 'surname', 'email', 'image', 'bio']

data/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from .models import Post
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.views.generic.edit import CreateView
from django.shortcuts import redirect
from .forms import PostForm, LoginForm
from .forms import SignupForm, LoginForm
from data.models import ProfileData
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import FormView
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User

# Create your views here.
class CreatePost(CreateView):
    form_class = PostForm
    template_name = 'data/create_post.html'
    success_url = '/home/'
    
    def form_invalid(self, form):
        print(form.errors)
        return super().form_invalid(form)
    
class HomeFeed(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'data/feed.html'
    context_object_name = 'posts'
    success_url = '/home/'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from .forms import SignupForm

class SignUp(FormView):
    template_name = 'registration/signup.html'
    form_class = SignupForm
    success_url = '/login/'  # Replace with the appropriate success URL

    def form_valid(self, form):
        user =form.save()
        print(f'User created ={user.username}')
        return super().form_valid(form)
    
    def form_invalid(self, form):
        print(form.errors)
        return super().form_invalid(form);
class LoginView(FormView):
    template_name = 'registration/login.html'
    success_url = '/home/'
    form_class = LoginForm 
    
    def form_valid(self, form):
        # Get the cleaned data
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        # Authenticate the user
        user = authenticate(self.request, username=username, password=password)
        if user:
            login(self.request, user) 
        return redirect(self.success_url)  # Log the user  # Redirect to success_url

    
        

profiles/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from data.models import ProfileData
from django.views.generic import DetailView, CreateView
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView






class ProfileView(LoginRequiredMixin, ListView):
    template_name = 'profiles/profiles.html'
    model = ProfileData
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profiles'] = ProfileData.objects.all()
        return context
    
    # def get_queryset(self):
    #     return ProfileData.objects.all()
    
class AdminProfile(TemplateView):
    template_name = 'profiles/profile.html'
    model = ProfileData
    context_object_name = 'profile_detail'
    
    def get_object(self, queryset=None):
        return ProfileData.objects.get(user=self.request.user)
class ProfileDetail(DetailView):
    model = ProfileData
    template_name = 'profiles/detailed-profile.html'
    context_object_name = 'detail-profile'
    
    def get_object(self, queryset=None):
        return ProfileData.objects.get(user__pk=self.kwargs['pk'])
    
class ProfileUpdateView(LoginRequiredMixin, CreateView):
    model = ProfileData
    template_name = 'profiles/profile.html'
    context_object_name = 'profile'
    success_url = reverse_lazy('profile')
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)




    

data/templates/custom/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    {% block content %}
    
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script>
        document.getElementById('file-upload').addEventListener('change', function(event) {
    var file = event.target.files[0]; // Get the selected file
    var reader = new FileReader(); // Create a new FileReader

    reader.onload = function(e) {
        var img = document.getElementById('image-preview'); // Get the image element
        img.src = e.target.result; // Set the image source to the file's data URL
        img.style.display = 'block'; // Show the image preview
    };

    if (file) {
        reader.readAsDataURL(file); // Read the file as a Data URL (base64 encoded)
    }
});
    </script>
</body>
</html>

data/templates/data/feed.html
{% extends 'custom/base.html' %}
{% load thumbnail %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}
{% block content %}

<div class="content1">
    <nav class="navbar">
        <h1>Make It Personal</h1>
    </nav>
    {% for post in posts %}
    {% if post.image %}
    <div class="container-fluid text-center p-0 feed-post shadow-lg" style=" background-image: linear-gradient(180deg, 
rgba(0, 0, 0, 0.5) 0%, 
rgba(0, 0, 0, 0.3) 100%),
url('{{ post.image.url }}');
background-repeat: no-repeat;
background-size:cover;">
        {% endif %}
        <div class="feed-pro-container">
            <a href="{% url 'profiles:detail' pk=post.pk %}">
                {% if post.user.profile.image %}
                <img src="{{ post.user.profile.image.url }}" class="rounded-circle feed-pro">
                {% else %}
                <div class="empty-placeholder feed-pro rounded-circle"></div>
                {% endif %}
            </a>
        </div>
    </div>
    <p class="card-text border-0 ">{{post.caption}} ~ {{user.username}}</p>
    {% endfor %}
    
</div>
{% include 'includes/nav.html' %}
{% endblock %}

templates/data/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#000000">
    <title>Document</title>
   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    {% block content %}
    
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script>
function previewImage() {
  const fileInput = document.getElementById('image');
  const file = fileInput.files[0];
  const preview = document.getElementById('image-preview');
  
  // Check if a file is selected
  if (file) {
    const reader = new FileReader();
    
    // When the file is loaded, display the image
    reader.onload = function(e) {
      preview.src = e.target.result;
      preview.style.display = 'block'; // Show the image
    }
    
    reader.readAsDataURL(file); // Read the file as a data URL
  } else {
    preview.style.display = 'none'; // Hide if no file is selected
  }
}
document.addEventListener('DOMContentLoaded', function() {
  const form = document.getElementById('signup-form');
  const image = document.getElementById('svg-image');
  const btn = document.getElementById('signup-button');

  btn.addEventListener('click', function(e) {
  e.preventDefault();
    image.classList.remove('hidden');
    image.classList.add('visible');
    setTimeout(() => {
      form.submit();
    }, 3000);    
     // Hide the image
  });
})
    </script>
</body>
</html>

templates/data/create_post.html
{% extends 'data/base.html' %}
{% load static %}

{% block content %}
<div class="content1">
    <div class="nav1">
        <a href="{% url 'home' %}" class="nav-link">Feed</a>
        <a href="{% url 'create_post' %}" class="nav-link">Post</a>
        <a href="{% url 'profiles:profiles' %}" class="nav-link">Users</a>
        <a href="{% url 'profiles:profile' %}" class="nav-link">Profile</a>
      </div>
    <nav class="navbar">
        <h1>What Got Your Attention</h1>
    </nav>
    <!-- custom_form.html -->
    <form method="post" action="{% url 'create_post' %}" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="custom-form-field">
        <label for="name">Name:</label>
        <input type="text" name="name" id="name" required class="custom-input" placeholder="Enter your name" class>
    </div>

        <div class="custom-form-field">
            <div class="create_image1">
                <!-- <label for="image">Image:</label> -->
                <input type="file" name="image" id="image" required class="custom-input" style="display: none;">
                <button type="button" class="custom-btn" onclick="document.getElementById('image').click();">Upload Image</button>
            </div>
        </div>
            <br>
            <br>
            <br>
        <div class="custom-form-field">
            <label for="caption">Caption</label>
            <textarea name="caption" id="message" required class="custom-textarea"
                placeholder="Enter your message"></textarea>
        </div>

        <button type="submit" class="submit-btn">Submit</button>
    </form>
</div>
{% endblock %}

templates/data/feed.html
{% extends 'data/base.html' %}
{% load thumbnail %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'admin/style.css' %}">
{% endblock %}
{% block content %}

<div class="content1">
    <!-- {% include 'includes/nav.html' %} -->
    <div class="nav1">
        <a href="{% url 'home' %}" class="nav-link">Feed</a>
        <a href="{% url 'create_post' %}" class="nav-link">Post</a>
        <a href="{% url 'profiles:profiles' %}" class="nav-link">Users</a>
        <a href="{% url 'profiles:profile' %}" class="nav-link">Profile</a>
      </div>
    <nav class="navbar">
        <h1>Make It Personal</h1>
    </nav>
    {% for post in posts %}
    {% if post.image %}
    <div class="container-fluid text-center p-0 feed-post shadow-lg" style=" background-image: linear-gradient(180deg, 
rgba(0, 0, 0, 0.5) 0%, 
rgba(0, 0, 0, 0.3) 100%),
url('{{ post.image.url }}');
background-repeat: no-repeat;
background-size:cover;">
        {% endif %}
        <div class="feed-pro-container">
            <a href="{% url 'profiles:detail' pk=post.pk %}">
                {% if post.author.profile.image %}
                <img src="{{ post.user.profile.image.url }}" class="rounded-circle feed-pro">
                {% else %}
                <div class="empty-placeholder feed-pro rounded-circle"></div>
                {% endif %}
            </a>
        </div>
    </div>
    <p class="card-text border-0 ">{{post.caption}} ~ {{author.username}}</p>
    {% endfor %}
    
</div>

{% endblock %}

templates/includes/nav.html
{% extends "data/base.html" %}
{% load static %}
{% block content %}
<div class="sticky-nav">
    <a href="{% url 'home' %}" class="nav-link">Feed</a>
    <a href="{% url 'create_post' %}" class="nav-link">Post</a>
    <a href="{% url 'profiles:profiles' %}" class="nav-link">Users</a>
    <a href="{% url 'profiles:profile' %}" class="nav-link">Profile</a>
  </div>
{% endblock %}

templates/profiles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#000000">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/profiles/detailed-profile.html
{% extends 'data/base.html' %}
{% load static %}
{% block content %} 
    {{ profile_detail.user}}
{% include 'includes/nav.html' %}
{% endblock %}

templates/profiles/profile.html
{% extends 'data/base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'admin/style.css' %}">
{% endblock %}
{% block content %}
    <div class="content1">
        <div class="nav1">
            <a href="{% url 'home' %}" class="nav-link">Feed</a>
            <a href="{% url 'create_post' %}" class="nav-link">Post</a>
            <a href="{% url 'profiles:profiles' %}" class="nav-link">Users</a>
            <a href="{% url 'profiles:profile' %}" class="nav-link">Profile</a>
          </div>
          <nav class="navbar">
            <h1>Profile</h1>
        </nav>
    <form method="post" enctype="multipart/form-data" action="{% url 'profiles:profile' %}">
        {% csrf_token %}
        
        <button type="submit">Save Changes</button>
    </form>
    <a href="{% url 'profiles:profile' %}">Cancel</a>
</div>
{% endblock %}

templates/profiles/profiles.html
{% extends 'data/base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'admin/style.css' %}">
{% endblock %}
{% block content %}
<div class="content1">
    <div class="nav1">
        <a href="{% url 'home' %}" class="nav-link">Feed</a>
        <a href="{% url 'create_post' %}" class="nav-link">Post</a>
        <a href="{% url 'profiles:profiles' %}" class="nav-link">Users</a>
        <a href="{% url 'profiles:profile' %}" class="nav-link">Profile</a>
      </div>
<nav class="navbar">
    <h1>Users</h1>
</nav>
{% for profile in profiles %}
    <a href="{% url 'profiles:detail' profile.user.pk %}">{{ profile.user }}</a>
    <hr>
{% endfor %}
</div>
{% endblock %}